version: '2'
services:
  web:
    build: .
    links:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_ADDRESS: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
